services:
  - type: web
    name: invoice-extractor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.enableCORS false
    envVars:
      - key: EURI_API_KEY
        sync: false   # Set secrets in the Render dashboard, not in code