services:
  - type: web
    name: invoice-extractor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    envVars:
      - key: EURI_API_KEY
        sync: false
